### ISSUE TITLE
Customers should be able to save the optional region while config option Allow to Choose State if It is Optional for Country is set to Yes only

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/graphql-ce#1032]
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

**Customers should be able to save the optional region while config option _Allow to Choose State if It is Optional for Country_ is set to _Yes_ only**
1. Navigate to Store -> Settings -> Configuration -> General -> General -> State Options
2. Find **United States** on the list. Press `<Ctrl>` or `<Cmd>` and remove the United States from the selection.
3. Change value for the **Allow to Choose State if It is Optional for Country** option to **No** and save the configuration.
4. Flush cache
4. Perform mutation as a Customer
```graphql
mutation {
  createCustomerAddress(
    input: {
      country_code: US
      firstname: "John"
      lastname: "Doe"
      city: "Culver City"
      region: {
        region_code: "CA"
        region_id: 12
        region: "California"
      }
      street: [
        "6161 West Centinella Avenue"
      ]
      postcode: "90230"
      telephone: "+1 555 555 5555"
      default_billing: true
      default_shipping: true
    }
  ) {
    country_code
    firstname
    lastname
    city
    region {
      region
      region_code
    }
    street
    postcode
    telephone
    default_billing
    default_shipping
  }
}
```
Expected result:
:heavy_check_mark: validation or region ignorance

Actual result:
:x: Region is present in the address
![image](https://user-images.githubusercontent.com/11827230/67681080-47b50600-f995-11e9-8d38-1a665840cd89.png)

**Comment by TomashKhamlai** [comment]
@lenaorobei, please confirm or modify expectations.

**Comment by lenaorobei** [comment]
@TomashKhamlai please check latest `2.3-develop`. This issue should be fixed.

**Comment by TomashKhamlai** [comment]
@lenaorobei, case 3 is still reproducible
![image](https://user-images.githubusercontent.com/11827230/68599758-d2bff100-04a9-11ea-9528-1983c6b9958e.png)
